name:                cgi-tp
version:             0.1.0.0
github:              "gianlucagiorgolo/cgi-tp"
license:             MIT
author:              "Gianluca Giorgolo"
maintainer:          "gianluca.giorgolo@gmail.com"
copyright:           "2019 Gianluca Giorgolo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cgi-tp#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5 && <= 0.6.0.1
- mtl >= 2.1.2 && <= 2.2.2
- xhtml >= 3000.2.1 && <= 3000.2.2.1
- blaze-html == 0.9.1.1

library:
  source-dirs: src

executables:
  cgi-tp-exe:
    main:                CgiTP.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optl-static
    dependencies:
    - cgi-tp
    - containers >= 0.5 && <= 0.6.0.1
    - mtl >= 2.1.2 && <= 2.2.2
    - filepath >= 1.3.0.1 && <= 1.4.2.1
    - directory >= 1.2.0.1 && <= 1.3.3.0
    - transformers >= 0.3.0.0 && <= 0.5.5.0
    - xhtml >= 3000.2.1 && <= 3000.2.2.1
    - cgi >= 3001.1.8.4 && <= 3001.3.0.3

tests:
  cgi-tp-test:
    main:                TestTP.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cgi-tp
    - QuickCheck == 2.12.6.1
    - HUnit == 1.6.0.0
